name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Debug Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generating Dockerfile from Modusfile
      run: target/debug/modus transpile Modusfile 'all("frontend", "release")' > /tmp/modus-frontend.Dockerfile && cat /tmp/modus-frontend.Dockerfile
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build frontend
      if: github.event_name != 'pull_request'
      run: >
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 10) &&
        IMAGE_REF=ghcr.io/$GITHUB_REPOSITORY-buildkit-frontend:$SHORT_SHA &&
        docker build -t $IMAGE_REF -f /tmp/modus-frontend.Dockerfile . &&
        docker tag $IMAGE_REF ghcr.io/$GITHUB_REPOSITORY-buildkit-frontend:latest &&
        docker push $IMAGE_REF
